# Generated by Django 4.0.2 on 2022-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('view', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night')], default='M', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='finch',
            options={'verbose_name': 'finch', 'verbose_name_plural': 'finches'},
        ),
    ]
