# Generated by Django 4.0.2 on 2022-02-08 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watching_alter_finch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='watching',
            name='finch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.finch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watching',
            name='date',
            field=models.DateField(verbose_name='Viewing Date'),
        ),
    ]
